version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: person1
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data