ALTER TABLE address ALTER COLUMN street  NOT NULL;
ALTER TABLE address ALTER COLUMN district  NOT NULL DROP UNIQUE;
ALTER TABLE address ALTER COLUMN cep NOT NULL;
ALTER TABLE address ALTER COLUMN number NOT NULL DROP UNIQUE;
ALTER TABLE address ALTER COLUMN complement NOT NULL;
ALTER TABLE address ALTER COLUMN city  NOT NULL;
ALTER TABLE address ALTER COLUMN uf  NOT NULL;
